import setuptools

setuptools.setup(
    name='my-iot',
    version='0.12.0',
    author='Pavel Perestoronin',
    author_email='eigenein@gmail.com',
    description='Yet another home automation',
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    url='https://github.com/eigenein/my-iot',
    packages=setuptools.find_packages(exclude=['tests']),
    package_data={
        '': ['*'],
    },
    python_requires='>=3.7',
    install_requires=[
        'aiohttp',
        'aiohttp_jinja2',
        'click',
        'loguru',
        'pygal',
        'ujson',
        'aiohttp-sse-client',
        'passlib',
        'aioping',
        'sqlitemap',
        'pydantic[ujson]',
        'u-msgpack-python',
        'pytz',
        'pprintpp',
    ],
    extras_require={
        'dev': ['pip-tools', 'isort', 'ipython', 'twine', 'flake8', 'pytest'],
    },
    entry_points={
        'console_scripts': [
            'my-iot = my_iot.__main__:main',
            'my-iot-utils = my_iot.utils:main',
        ],
    },
    classifiers=[
        'Development Status :: 3 - Alpha',
        'Environment :: Console',
        'Environment :: Web Environment',
        'Intended Audience :: Developers',
        'Intended Audience :: Information Technology',
        'Intended Audience :: System Administrators',
        'License :: OSI Approved :: MIT License',
        'License :: OSI Approved',
        'Operating System :: OS Independent',
        'Programming Language :: Python :: 3 :: Only',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.7',
        'Topic :: Home Automation',
    ],
    zip_safe=True,
)
